language: go
dist: xenial
os : linux
go:
  - 1.14.x
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
before_install:
  - go get github.com/fzipp/gocyclo
script:
  - go test -v -race ./... -coverprofile=coverage.txt -covermode=atomic
  - bash <(curl -s https://codecov.io/bash)
